### ISSUE TITLE
Broken OneBranch ARM builds

### ISSUE THREAD

**Issue by nigriMSFT** [microsoft/win-net-test#23]
9fa7cc79b3b2f042e493f79fd3844eaf9a12fcd6 broke the OneBranch ARM builds

**Comment by nibanks** [comment]
I sent email internally to some folks (cc'ed you) to try to get some help.

**Comment by nigriMSFT** [comment]
Workaround was to disable ARM64X build. Resolved by https://github.com/microsoft/undocked/commit/45f60a4c3bb636a995308f5d609c8c22abc2eebe and  7518e8ea81ca474163447682c3d7b041a5bf7eef
